/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 成員登入與註冊（無密碼機制）
         * @description 依據部門、名字、性別進行登入。若資料庫中無此組合，系統會自動調用 CodeUtils 生成全新 UUID 註冊新成員，並回傳該 UUID；若已存在，則直接回傳舊成員的 UUID。前端收到後應存入 LocalStorage。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description 使用者所屬的教會部門
                         * @example 青年部
                         */
                        dept: string;
                        /**
                         * @description 使用者名字
                         * @example 阿法哥
                         */
                        name: string;
                        /**
                         * @description 使用者性別
                         * @example 男
                         */
                        gender: string;
                    };
                };
            };
            responses: {
                /** @description 登入或註冊成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description 後端核發的唯一識別憑證 (UUID)，前端後續請求皆需攜帶
                             * @example e45a2c3b-8912-4d3e-a123-426614174000
                             */
                            id?: string;
                            /** @example 阿法哥 */
                            name?: string;
                            /** @example 青年部 */
                            dept?: string;
                        };
                    };
                };
                /** @description 請求參數缺失 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 上傳單次任務紀錄（增量輸入）
         * @description 使用者每次做完條件後填寫的數據。後端採流水帳設計，收到後會直接存入新 Row，不會覆蓋舊有數據。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 儲存在前端 LocalStorage 的使用者 UUID 憑證 */
                    "X-Member-Id": components["parameters"]["X-Member-Id"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description 當下登記的校園名稱（請前後端字串嚴格統一）
                         * @example 台大
                         * @enum {string}
                         */
                        campus: "台大" | "師大" | "台科大";
                        /**
                         * @description 本次新增的禱告時間（分鐘）。若未填則預設為 0
                         * @example 20
                         */
                        prayerMinutes?: number;
                        /**
                         * @description 本次新增的傳道/生命管理次數（次）。若未填則預設為 0
                         * @example 1
                         */
                        evangelismCount?: number;
                        /**
                         * @description 今日體會/見證/感動心聲
                         * @example 下午跟學弟分享話語，順利完成傳道！
                         */
                        realization?: string;
                    };
                };
            };
            responses: {
                /** @description 紀錄儲存成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example 紀錄已儲存 */
                            message?: string;
                        };
                    };
                };
                /** @description 業務邏輯阻擋（例如：5/20活動尚未開始或使用者 ID 錯誤） */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example 活動尚未正式開始，統一開放登錄時間為 5/20 */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢個人各校園的總累積進度
         * @description 前端用來計算「個人進度條比例」以及「判斷是否解鎖兩款明信片（禱告>=30分、傳道>=1次）」的核心 API。
         */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description 儲存在前端 LocalStorage 的使用者 UUID 憑證 */
                    "X-Member-Id": components["parameters"]["X-Member-Id"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功取得個人累積數據 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 台大 */
                            campus?: string;
                            /**
                             * @description 該校園歷次上傳的禱告分鐘數總和
                             * @example 35
                             */
                            totalPrayerMinutes?: number;
                            /**
                             * @description 該校園歷次上傳的傳道次數總和
                             * @example 1
                             */
                            totalEvangelismCount?: number;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/realizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 一次倒出個人所有的歷史體會紀錄
         * @description 用於「歷史回顧」分頁。回傳使用者寫過的所有體會，依時間由新到舊排序，內含學校標籤與精確時間。
         */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description 儲存在前端 LocalStorage 的使用者 UUID 憑證 */
                    "X-Member-Id": components["parameters"]["X-Member-Id"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功取得歷史體會清單 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 該段體會所屬的學校
                             * @example 台大
                             */
                            campus?: string;
                            /** @example 早晨在椰林大道禱告，很有感動！ */
                            realization?: string;
                            /**
                             * Format: date-time
                             * @description 後端標準 LocalDateTime 格式，請前端自行依需求排版顯示
                             * @example 2026-05-17T17:27:00Z
                             */
                            createdAt?: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/stats/global": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢全體參與狀況大盤統計（即時更新）
         * @description 供應首頁或統計區域的大圖表數據。包含實際參與人數、總傳道次數、全教會總解鎖明信片張數，以及三間學校各自的總禱告累計時間。本 API 不需驗證 Header。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功取得全局統計數據 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 實際有送出過至少一次任務紀錄的不重複成員總人數
                             * @example 145
                             */
                            totalParticipants?: number;
                            /**
                             * @description 全體成員累計的總傳道次數
                             * @example 88
                             */
                            totalEvangelism?: number;
                            /**
                             * @description 全體成員目前總共獲得的數位明信片總張數（禱告、傳道分開計算）
                             * @example 210
                             */
                            totalPostcardsUnlocked?: number;
                            /**
                             * @description 台大目前全體累計禱告總分鐘數（目標為 40 小時 = 2400 分鐘）
                             * @example 2450
                             */
                            ntuTotalPrayer?: number;
                            /**
                             * @description 師大目前全體累計禱告總分鐘數
                             * @example 1800
                             */
                            ntnuTotalPrayer?: number;
                            /**
                             * @description 台科大目前全體累計禱告總分鐘數
                             * @example 950
                             */
                            ntustTotalPrayer?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: {
        /** @description 儲存在前端 LocalStorage 的使用者 UUID 憑證 */
        "X-Member-Id": string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
